#!/bin/bash

Printf() {
    [ "$silent" = "no" ] && /usr/bin/printf "$@"
}

Main() {
    local silent=no

    case "$1" in
        --silent) silent=yes ;;
    esac

    sleep 0.1

    # Find all yad processes for user
    mapfile -t yads < <(pgrep -u "$LOGNAME" -a yad)

    for line in "${yads[@]}"; do
        pid=$(echo "$line" | awk '{print $1}')
        cmd=$(echo "$line" | cut -d' ' -f2-)

        # kill only clearly orphaned/simple yad instances
        if [[ "$cmd" == "/usr/bin/yad" || "$cmd" == "yad" ]]; then
            Printf "Killing yad zombie: %s\n" "$line"
            kill "$pid"
        fi
    done
}

Main "$@"
